version: '3'
services:
  planet-venus:
    build: .
    volumes:
      - static-content:/var/planet/www
      - ./:/var/planet/jakartablogs.ee
  nginx:
    image: nginx
    ports:
      - 80
    volumes:
      - static-content:/usr/share/nginx/html:ro
 
volumes:
  static-content: